version: 2
jobs:

  test-php74:
    docker:
      - image: circleci/php:7.4-cli
      - image: rabbitmq

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install PHPUnit
          command: |
            composer require phpunit/phpunit:7.5.17 --no-update

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            rm -Rf var/*
            php vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - test-php74